### ISSUE TITLE
Clarifying behavior wrt Redux Connect

### ISSUE THREAD

**Issue by oyeanuj** [adam-26/react-router-dispatcher#17]
Hi @adam-26, thanks for putting it out there! I am currently using `redux-connect` and wondering if I need to migrate to this library to be able to upgrade to RR4. 

I am not sure if I was fully following the terminology of `routeComponent`, `routeContainer`, and `routeDispatcher` actions. It seems that the data dependencies need to be dispatched at route level, but then how does it work for components which may be route components or embedded within other components?

Here is an example:

Lets say, I have the following set up:
```jsx
<List>
  <Post />
  <Post />
<List>

<Post>
 <Author />
 <Body />
 <Comments />
</Post>
```
Say, in the current `redux-connect` world, I have an `asyncConnect` decorator on `List`, `Post`, `Author`, and `Comments` - which ensures that whether they are invoked directly on a url (/posts/123) or as part of a list (/list), the `asyncConnect` method will fetch the data for them.

How does that model change in this world, given the tie-in to routes? Would I need something like this - 
```jsx
export default withDispatcher((store, match) => {
  return Promise.all([
    Post.routeDispatcher(store, match)
   // And the dispatcher internally calls 
   // Author.routeDispatcher & Comments.routeDispatcher
  ]);
})(ListComponent);
```

And what then happens if someone directly goes to `/post/123` or `/author/123` or `/post/123/comments`?

Sorry for the long post, but I hope it will help anyone else coming from that library (and we could maybe even have a section detailing the differences between the two libraries?).

**Comment by adam-26** [comment]
Hi @oyeanuj, 

It's a long reply, let me know if you have more questions. Be sure to read the **Recommendations**.

For clarification (and let me know if this isn't clear - the docs need to be improved)
 * **routeDispatcher**: is a function that has the sole responsibility of dispatching **route actions**
 * **route action (creator)**: an action used by a routeDispatcher, a route action creator should be defined for each configured route (as a general rule) - i probably need to correct the use of the term _route action_ to be _route action creator_ in the documentation.
 * **routeComponent**: is a component used in a route configuration

### React Components and Redux Containers

So, for your example above you define the following **redux connected containers**:
> I use _container_ in the redux context, in that a container is used to **connect** redux state to a component

**AuthorContainer**:
`<Author />` (Component)

**CommentsContainer**:
`<Comments />` (Component)

**PostContainer**:
```
<Post>
 <AuthorContainer />
 <Body />
 <CommentsContainer />
</Post>
```

**PostsContainer**:
````
<List>
  <PostContainer />
  <PostContainer />
<List>
````

### Routes

You have defined the **routes**, and their current container usage:
```
1. /posts -> PostsContainer
2. /post/:id -> PostContainer
3. /post/:id/comments -> CommentsContainer
4. /author/:id -> AuthorContainer
```
> I've numbered them so I can refer to specific routes throughout the reply


There are **2 possible approaches**:
 1. Routes are aware of the components they contain (my preferred approach)
 2. Components are aware of the routes that use them (like redux-connect, redux-async-connect)

## Approach 1
Routes must be aware of the components they contain


### Route Components

Given the defined redux containers and routes, we need to define 4 **RouteComponents**:

```js
// 1. PostsRouteComponent - /posts 

export default withDispatcher(({dispatch}, match) => {
  return dispatch(getPosts());
})(PostsContainer);
```

```js
// 2. PostRouteComponent - /posts/:id

export default withDispatcher(({dispatch}, {params}) => {
  return dispatch(getPost(params.id));
})(PostContainer);
```

```js
// 3. CommentsRouteComponent - /posts/:id/comments

export default withDispatcher(({dispatch}, {params}) => {
  return dispatch(getPostComments(params.id));
})(CommentsContainer);
```

```js
// 4. AuthorRouteComponent - /author/:id

export default withDispatcher(({dispatch}, {params}) => {
  return dispatch(getAuthor(params.id));
})(AuthorContainer);
```
> A clean way to organize this is to use a /routes directory, and /routes/index.js defines the route config.

I intentionally keep the **routeComponents** dumb. Follow the redux best practices, let the **route action creators** handle the logic.

### Route Action Creators

Next, we need to define the **route action creators**, these examples assume the use of middleware such as [redux-thunk]() or [redux-saga]()

_Each route action is responsible for dispatching the action(s) required to load all data for a route_

```js
// 1. getPostsRouteAction

// import the redux action(s) required for the route
import loadPosts from '../actions/loadPosts';

export default function getPosts() {
  return function (dispatch) {
    return dispatch(loadPosts());
  }
}
```

```js
// 2. getPostRouteAction

// import the redux action(s) required for the route
import loadPosts from '../actions/loadPost';

export default function getPost(postId) {
  return function (dispatch) {
    return dispatch(loadPost(postId));
  }
}
```
> the **loadPost** action would also dispatch the **loadPostComments** and **loadAuthor** actions that are used in the following route actions

```js
// 3. getPostCommentsRouteAction

// import the redux action(s) required for the route
import loadPostComments from '../actions/loadPostComments';

export default function getPostComments(postId) {
  return function (dispatch) {
    return dispatch(loadPostComments(postId));
  }
}
```

```js
// 4. getAuthorRouteAction

// import the redux action(s) required for the route
import loadAuthor from '../actions/loadAuthor';

export default function getAuthor(authorId) {
  return function (dispatch) {
    return dispatch(loadAuthor(authorId));
  }
}
```
> In the above examples, **loadPosts**, **loadPost**, **loadPostComments** and **loadAuthor** action creators all _fetch_ data using redux middleware.

These route action creators may seem redundant as they only dispatch a single action creator, and **if you're working on a small project, they may not be required**, however as your project grows and you need to load non-related data for a route (for example; content and side-content and advertising) then this level of indirection can help to maintain a clean code base.

**important**: Each route should be self-contained. You should be able to modify any route component or route action creator without impacting the behavior of another route.

@oyeanuj, this is where your **components tie together** - it's ultimately the responsibility of **action creators** being associated with a specific route.

A specific example of the **loadPost** action creator:
```js
export default function loadPost(postId) {
  return function(dispatch) {
    return Promise.all([
      dispatch(loadPostById(postId)); // load the post from an API or database
      dispatch(loadPostCommentsById(postId));
      dispatch(loadAuthorByPostId(postId)); // use the postId so no dependency on other actions
    ]);
  }
}
```

As a convention, i usually begin the name of all _route action creators_ with **get**, and standard action creators that load data from an API or data store **load**.

### Recommendations

This becomes much easier to understand if you write all the code for a single route in a single file:

```js
// file: ./routes/GetPostsRoute.js

import { withDispatcher } from 'react-router-dispatcher';
import PostsContainer from '../modules/PostsContainer';
import loadPosts from '../actions/loadPosts';

// getPosts route action creator - export for testing
export const getPosts = function () {
  return function (dispatch) {
    return dispatch(loadPosts());
  }
}
// Or, using ES6: const getPosts = () => (dispatch) => dispatch(loadPosts());

// getPosts route component
export default withDispatcher(({dispatch}, match) => {
  return dispatch(getPosts());
})(PostsContainer);
```
> I **recommend defining your route configuration in the file** /routes/index.js

```js
// file: ./routes/index.js

import GetPostsRoute from './GetPostsRoute';

export default [
  component: RootComponent
  routes: [{
    path: '/posts',
    exact: true,
    component: GetPostsRoute
  }]
];
```

## Approach 2
Components must be aware of the routes that use them

This is more similar to redux-connect and redux-async-connect.

This allows you to define the routeDispatcher and route action creator with the container, **but** to support a component being used in multiple routes it requires you to be clever with the way you name your route parameters. 

For example; using the AuthorContainer as an example:
With the route config (**important**: note the names of the url parameters)
```js
export default [
 ...
  routes: [{
    path: '/posts/:postId',
    exact: true,
    component: GetPostRoute
  }, {
    path: '/author/:authorId',
    exact: true,
    component: GetAuthorRoute
  }]
];
```

it could be loaded using a `postId` or a `authorId` parameter:

```js
// AuthorContainer

// connect to redux
const AuthorContainer = connect(mapStateToProps)(AuthorComponent);

// getAuthor route action creator
const getAuthor = ({authorId, postId}) => {
  return (dispatch) => {
    if (authorId) {
      return dispatch(loadAuthorById(authorId));
    }

    if (postId) {
      return dispatch(loadAuthorByPostId(postId));
    }

    return Promise.reject(new Error('Invalid url parameters for Author.'));
  }
}

// define the routeDispatcher for the AuthorContainer
export default withDispatcher(({dispatch}, {params}) => {
  return dispatch(getAuthor(params));
})(AuthorContainer);

```

```js
// PostComponent.js

import Author from './AuthorContainer';

// export any components that require route data
export {
  Author
};

export default class PostComponent extends React.Component {
//....
  render() {
    // ... uses the Author Container
    <Author ... />
  }
}
```

Then, the **Post** container would use the Author container:

```js
// PostContainer.js

import PostComponent from './PostComponent';

// connect to redux
const PostContainer = connect(mapStateToProps)(PostComponent);

// getAuthor route action creator
const getPost = (postId) => {
  return (dispatch) => {
    return dispatch(loadPostById(postId));
  }
}

// define the routeDispatcher for the AuthorContainer
export default withDispatcher(store, match) => {
  return Promise.all([
    store.dispatch(getPost(params.postId)),
    store.dispatch(PostComponent.Author.routeDispatcher(store, match))
  ]);
})(AuthorContainer);
```

### Summary

My personal preference is **approach 1**, I believe it results in cleaner code that is easier to test. 

Routes add a layer of abstraction over a regular redux style project.
 * routes should remain dumb
 * code for fetching data should be contained in action creators

### Comparison to redux-connect

Where the redux-connect API was designed to allow you to simply load data for a component, the API of this package has been designed to encourage a stricter redux approach to loading data for routes. Given the changes to react-router v4+ I think this API provides for a cleaner approach as it allows you to easily handle the restrictions imposed by react-router.

**Comment by oyeanuj** [comment]
@adam-26 Thank you so much for such a detailed and quick response, I really do appreciate it! It definitely helps in understanding the concepts more clearly.

I am clearly coming from the 'component takes care of its own data' world where a route can then comprise any component. I think the one BIG advantage of that world to me has been that it allows me operations like lets say, someone is writing a post, and I want to embed another post - that is not reflected in the route, but once I insert `<PostContainer id = {postId} />`, I know that the embed will show up properly with its own data. I'm not saying that the package needs to support such usecases but just giving an example of where I was coming from. 

In general, it encouraged that the routes not be too smart. For example, if a post doesn't have comments, then we don't need to fetch that promise initially (like in the example above).

Another much smaller advantage was that instead of doing the following:
```jsx
<List>
  <PostRouteComponent ... />
  <PostRouteComponent ... />
  ...
</List>
```
you can instead write:
```jsx
<List>
  <PostContainer ... />
  <PostContainer ... />
  ...
</List>
```
Would it be fair to assume that the focus of this library would remain as route-based data fetching?

---

Finally, is it fair to say route action creators is just named such to illustrate that they are responsible for fetching data for the route - rather than regular action creators tied to containers in the `redux-connect` world?

---
Again, thank you for taking the time to explain!

**Comment by adam-26** [comment]
Hi @oyeanuj, I will answer the questions you asked above, but first can you tell me if you are using redux-connect for server-side rendering, or are you only using it for client-side rendering?

**Comment by adam-26** [comment]
@oyeanuj, in answer to your questions above:

From your example,
```js
<List>
  <PostRouteComponent ... />
  <PostRouteComponent ... />
  ...
</List>
```
You don't **need** to include the word _Route_ in your component names, it just to emphasize the differences for the examples.

If you're coming from redux-connect, you may even prefer to apply the `@withDispatcher(...)` function as an annotation to an existing Component.

Given the limitations imposed by react-router v4+ (and I don't think there's anything wrong with the limitations), this library will remain focused on route-based data fetching.

Secondly, yes - _route action creators_ are a concept - only to differentiate them from standard action creators.

I'd be curious to see your existing implementation of your `<Author />` component, I completely understand what you mean by components taking care of their own data. But in your original example you used the `<Author />` component in multiple routes. **How** does the component know what data to load when the routes contain different parameter names?

A library like (react-async-bootstrapper)[https://github.com/ctrlplusb/react-async-bootstrapper] might be a better fit if your primary concern is having components handle their own data. You could use that with (react-jobs)[https://github.com/ctrlplusb/react-jobs].

If performance is more of a concern, or if you want stricter separation of concerns then this package would probably be better suited to your needs.

**Comment by oyeanuj** [comment]
@adam-26 thank for the response, and for engaging in a discussion!

> I'd be curious to see your existing implementation of your `<Author />` component, I completely understand what you mean by components taking care of their own data. But in your original example you used the <Author /> component in multiple routes. How does the component know what data to load when the routes contain different parameter names?

Essentially, the `<Author />` component, takes in an `authorId` and then in the `redux-connect` decorator, it checks if the author information is in the Redux store, and if not, it fetches it from the backend (the most common case). So, if the `Post` component is embedding `Author`, it will pass the `authorId` as a prop. If it is the author page, then the `authorId` would come from the route itself. 

And maybe that is a good example of _'components handling their own data'_. It seems like with `react-router-dispatcher`, the `List` and `Post` would need to know about `Author`'s data fetching logic/requirements?

> A library like [react-async-bootstrapper](https://github.com/ctrlplusb/react-async-bootstrapper) might be a better fit if your primary concern is having components handle their own data. You could use that with [react-jobs](https://github.com/ctrlplusb/react-jobs).

I've had those libraries on my list to delve into, thanks for the reminder 😃
