### ISSUE TITLE
Question: Why child route components not rendered?

### ISSUE THREAD

**Issue by shye0000** [adam-26/react-router-dispatcher#18]
Hi @adam-26 , I'm new to React and trying to use "react-router-dispatcher" for async server rendering, I would like to define the routes with nested style. Something like this:
```
const routes = [
    {
        path: '/',
        exact: true,
        component: IndexPage,
        // child routes
        routes: [{
            path: '/books',
            exact: true,
            component: BooksRouteComponent
        }, {
            path: '/authors',
            exact: true,
            component: AuthorsRouteComponent
        }]
    }, {
        path: '/login',
        exact: true,
        component: Login
    }
];
```

And this is my App.js:
```
export default ({store, routes, history}) => {
    const supportsHistory = typeof window !== 'undefined' && 'pushState' in window.history;
    return (
        <Provider store={store}>
            <ConnectedRouter history={history} forceRefresh={!supportsHistory}>
                <RouteDispatcher routes={routes} />
            </ConnectedRouter>
        </Provider>
    );
}
```

But the child routes are not rendered. Do I miss something?

**Comment by adam-26** [comment]
Hi @shye0000, [react-router-dispatcher](https://github.com/adam-26/react-router-dispatcher) uses [react-router-config](https://github.com/ReactTraining/react-router/tree/master/packages/react-router-config) for route configuration. [react-router-dispatcher](https://github.com/adam-26/react-router-dispatcher) delegates all routing to react-router. You should read the documentation there about configuring static routes.

But to me, it looks like your route configuration is incorrect... `/login` should be a **child** route of your root `/` route (as you've configured `/books` and `/authors`).

Hope this helps.
